import Document, { Html, Head, Main, NextScript } from 'next/document';
import Link from 'next/link';

export default class MyDocument extends Document {
  render() {
    return (
      <Html lang="en">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <body>
          <div className="logoContainer">
            <Link href="/">
              <a>
                <img src="/logo.svg" alt="Bitstamp" />
              </a>
            </Link>
          </div>
          
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}