import Document, { Html, Head, Main, NextScript } from 'next/document';

export default class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
          <title>Title</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <body>
          <div className="logoContainer">
            <img src="/logo.svg" alt="Bitstamp" />
          </div>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}